"use client"

import { useAccessibility } from "@/contexts/accessibility-context"

interface LanguageStrings {
  [key: string]: {
    [key: string]: string
  }
}

const translations: LanguageStrings = {
  es: {
    // Navigation
    "nav.dashboard": "Panel",
    "nav.sessions": "Sesiones",
    "nav.search": "Buscar Tutores",
    "nav.profile": "Perfil",
    "nav.settings": "Configuración",
    "nav.signOut": "Cerrar Sesión",
    "nav.signIn": "Iniciar Sesión",
    "nav.signUp": "Registrarse",
    "nav.home": "Inicio",
    "nav.about": "Acerca de",
    "nav.contact": "Contacto",
    "nav.help": "Ayuda",

    // Home Page
    "home.hero.title": "Aprende Sin Límites",
    "home.hero.subtitle":
      "Conéctate con tutores expertos para apoyo académico personalizado. Accesible, inclusivo y diseñado para cada estudiante.",
    "home.hero.getStarted": "Comenzar",
    "home.hero.findTutors": "Buscar Tutores",
    "home.features.title": "¿Por Qué Elegir TutorHub?",
    "home.features.subtitle":
      "Estamos comprometidos a hacer que la educación de calidad sea accesible para todos, con características diseñadas para todos los estudiantes.",
    "home.accessibility.title": "Comprometidos con la Accesibilidad",
    "home.accessibility.subtitle":
      "TutorHub está diseñado para ser accesible a todos los usuarios, incluidos aquellos con discapacidades. Seguimos las pautas WCAG 2.1 AA y mejoramos continuamente las características de accesibilidad de nuestra plataforma.",
    "home.contact.title": "Ponte en Contacto",
    "home.contact.subtitle": "¿Tienes preguntas? Estamos aquí para ayudarte a tener éxito.",

    // Features
    "features.expertTutors": "Tutores Expertos",
    "features.expertTutors.desc": "Conéctate con tutores calificados en todas las materias y niveles académicos.",
    "features.personalizedLearning": "Aprendizaje Personalizado",
    "features.personalizedLearning.desc": "Recibe atención individual adaptada a tu estilo y ritmo de aprendizaje.",
    "features.flexibleScheduling": "Horarios Flexibles",
    "features.flexibleScheduling.desc":
      "Reserva sesiones que se adapten a tu horario con opciones fáciles de reprogramación.",
    "features.qualityAssured": "Calidad Garantizada",
    "features.qualityAssured.desc":
      "Todos los tutores están verificados y calificados por estudiantes para garantizar la calidad.",
    "features.safeSecure": "Seguro y Protegido",
    "features.safeSecure.desc":
      "Tu privacidad y seguridad son nuestras principales prioridades con sesiones encriptadas.",
    "features.instantSupport": "Soporte Instantáneo",
    "features.instantSupport.desc": "Obtén ayuda cuando la necesites con nuestro sistema de soporte receptivo.",

    // Forms
    "form.required": "requerido",
    "form.email": "Correo Electrónico",
    "form.password": "Contraseña",
    "form.confirmPassword": "Confirmar Contraseña",
    "form.fullName": "Nombre Completo",
    "form.signIn": "Iniciar Sesión",
    "form.signUp": "Crear Cuenta",
    "form.loading": "Cargando...",
    "form.signingIn": "Iniciando sesión...",
    "form.creatingAccount": "Creando cuenta...",
    "form.sendMessage": "Enviar Mensaje",
    "form.sendingMessage": "Enviando mensaje...",
    "form.name": "Nombre",
    "form.subject": "Asunto",
    "form.message": "Mensaje",
    "form.category": "Categoría",
    "form.phone": "Teléfono",
    "form.save": "Guardar",
    "form.cancel": "Cancelar",
    "form.edit": "Editar",
    "form.delete": "Eliminar",
    "form.submit": "Enviar",
    "form.reset": "Restablecer",

    // Search
    "search.title": "Encuentra Tu Tutor Perfecto",
    "search.subtitle":
      "Busca en nuestra red de tutores calificados y verificados para encontrar la combinación perfecta para tus objetivos de aprendizaje.",
    "search.results": "Resultados de Búsqueda",
    "search.tutorsFound": "tutores encontrados",
    "search.bookSession": "Reservar Sesión",
    "search.sendMessage": "Enviar Mensaje",
    "search.viewProfile": "Ver Perfil",
    "search.loadMore": "Cargar Más Tutores",
    "search.noResults": "No se encontraron tutores",
    "search.tryDifferent": "Intenta con diferentes filtros de búsqueda",
    "search.filters": "Filtros",
    "search.clearFilters": "Limpiar Filtros",
    "search.priceRange": "Rango de Precio",
    "search.availability": "Disponibilidad",
    "search.rating": "Calificación",
    "search.experience": "Experiencia",
    "search.language": "Idioma",
    "search.location": "Ubicación",

    // Dashboard
    "dashboard.welcome": "Bienvenido de nuevo",
    "dashboard.subtitle": "Esto es lo que está pasando con tus sesiones de tutoría.",
    "dashboard.totalSessions": "Sesiones Totales",
    "dashboard.completed": "Completadas",
    "dashboard.upcoming": "Próximas",
    "dashboard.upcomingSessions": "Próximas Sesiones",
    "dashboard.noSessions": "No hay sesiones próximas",
    "dashboard.findTutors": "Buscar Tutores",
    "dashboard.viewSessions": "Ver Todas las Sesiones",
    "dashboard.recentActivity": "Actividad Reciente",
    "dashboard.quickStats": "Estadísticas Rápidas",
    "dashboard.thisWeek": "Esta Semana",
    "dashboard.thisMonth": "Este Mes",
    "dashboard.earnings": "Ganancias",
    "dashboard.students": "Estudiantes",

    // Sessions
    "sessions.title": "Mis Sesiones",
    "sessions.subtitle": "Gestiona tus sesiones de tutoría",
    "sessions.bookNew": "Reservar Nueva Sesión",
    "sessions.filter.all": "Todas las Sesiones",
    "sessions.filter.scheduled": "Programadas",
    "sessions.filter.completed": "Completadas",
    "sessions.filter.cancelled": "Canceladas",
    "sessions.filter.inProgress": "En Progreso",
    "sessions.status.scheduled": "Programada",
    "sessions.status.completed": "Completada",
    "sessions.status.cancelled": "Cancelada",
    "sessions.status.inProgress": "En Progreso",
    "sessions.status.noShow": "No Asistió",
    "sessions.viewDetails": "Ver Detalles",
    "sessions.joinMeeting": "Unirse a la Reunión",
    "sessions.reschedule": "Reprogramar",
    "sessions.cancel": "Cancelar",
    "sessions.markComplete": "Marcar Completada",
    "sessions.rateTutor": "Calificar Tutor",
    "sessions.rateStudent": "Calificar Estudiante",
    "sessions.sendMessage": "Enviar Mensaje",
    "sessions.notes": "Notas de la Sesión",
    "sessions.addNotes": "Agregar Notas",
    "sessions.saveNotes": "Guardar Notas",
    "sessions.feedback": "Comentarios",
    "sessions.submitFeedback": "Enviar Comentarios",
    "sessions.duration": "Duración",
    "sessions.price": "Precio",
    "sessions.tutor": "Tutor",
    "sessions.student": "Estudiante",
    "sessions.subject": "Materia",
    "sessions.date": "Fecha",
    "sessions.time": "Hora",
    "sessions.location": "Ubicación",
    "sessions.online": "En Línea",
    "sessions.inPerson": "Presencial",

    // Profile
    "profile.title": "Mi Perfil",
    "profile.subtitle": "Gestiona tu información personal y configuración de cuenta",
    "profile.personalInfo": "Información Personal",
    "profile.contactInfo": "Información de Contacto",
    "profile.professionalInfo": "Información Profesional",
    "profile.bio": "Biografía",
    "profile.specializations": "Especializaciones",
    "profile.experience": "Experiencia",
    "profile.education": "Educación",
    "profile.certifications": "Certificaciones",
    "profile.languages": "Idiomas",
    "profile.hourlyRate": "Tarifa por Hora",
    "profile.availability": "Disponibilidad",
    "profile.profilePicture": "Foto de Perfil",
    "profile.uploadPhoto": "Subir Foto",
    "profile.changePhoto": "Cambiar Foto",
    "profile.removePhoto": "Eliminar Foto",
    "profile.saveChanges": "Guardar Cambios",
    "profile.editProfile": "Editar Perfil",
    "profile.viewPublicProfile": "Ver Perfil Público",

    // Settings
    "settings.title": "Configuración",
    "settings.subtitle": "Gestiona las preferencias de tu cuenta y opciones de accesibilidad",
    "settings.general": "General",
    "settings.accessibility": "Accesibilidad",
    "settings.privacy": "Privacidad",
    "settings.account": "Cuenta",
    "settings.notifications": "Notificaciones",
    "settings.security": "Seguridad",
    "settings.theme": "Tema",
    "settings.language": "Idioma",
    "settings.fontSize": "Tamaño de Fuente",
    "settings.highContrast": "Alto Contraste",
    "settings.reduceMotion": "Reducir Movimiento",
    "settings.screenReader": "Lector de Pantalla",
    "settings.keyboardShortcuts": "Atajos de Teclado",
    "settings.exportData": "Exportar Datos",
    "settings.deleteAccount": "Eliminar Cuenta",
    "settings.changePassword": "Cambiar Contraseña",
    "settings.twoFactor": "Autenticación de Dos Factores",
    "settings.activeSessions": "Sesiones Activas",
    "settings.privacyControls": "Controles de Privacidad",
    "settings.dataManagement": "Gestión de Datos",

    // Booking
    "booking.title": "Reservar Sesión",
    "booking.subtitle": "Programa una sesión de tutoría",
    "booking.selectSubject": "Seleccionar Materia",
    "booking.selectDate": "Seleccionar Fecha",
    "booking.selectTime": "Seleccionar Hora",
    "booking.duration": "Duración",
    "booking.sessionType": "Tipo de Sesión",
    "booking.online": "En Línea",
    "booking.inPerson": "Presencial",
    "booking.description": "Descripción de la Sesión",
    "booking.specialRequests": "Solicitudes Especiales",
    "booking.totalCost": "Costo Total",
    "booking.bookSession": "Reservar Sesión",
    "booking.confirmBooking": "Confirmar Reserva",
    "booking.paymentMethod": "Método de Pago",
    "booking.cardNumber": "Número de Tarjeta",
    "booking.expiryDate": "Fecha de Vencimiento",
    "booking.cvv": "CVV",
    "booking.billingAddress": "Dirección de Facturación",

    // Accessibility
    "a11y.highContrast": "Alto Contraste",
    "a11y.reduceMotion": "Reducir Movimiento",
    "a11y.fontSize": "Tamaño de Fuente",
    "a11y.language": "Idioma de Interfaz",
    "a11y.colorVision": "Visión de Color",
    "a11y.customColors": "Colores Personalizados",
    "a11y.speechSettings": "Configuración de Voz",
    "a11y.keyboardShortcuts": "Atajos de Teclado",
    "a11y.skipToMain": "Saltar al contenido principal",
    "a11y.skipToNav": "Saltar a la navegación",
    "a11y.openMenu": "Abrir menú de accesibilidad",
    "a11y.closeMenu": "Cerrar menú de accesibilidad",

    // Common
    "common.on": "Activado",
    "common.off": "Desactivado",
    "common.yes": "Sí",
    "common.no": "No",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.close": "Cerrar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.clear": "Limpiar",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.warning": "Advertencia",
    "common.info": "Información",
    "common.confirm": "Confirmar",
    "common.back": "Volver",
    "common.next": "Siguiente",
    "common.previous": "Anterior",
    "common.continue": "Continuar",
    "common.finish": "Finalizar",
    "common.retry": "Reintentar",
    "common.refresh": "Actualizar",
    "common.view": "Ver",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.add": "Agregar",
    "common.remove": "Eliminar",
    "common.select": "Seleccionar",
    "common.choose": "Elegir",
    "common.upload": "Subir",
    "common.download": "Descargar",
    "common.print": "Imprimir",
    "common.share": "Compartir",
    "common.copy": "Copiar",
    "common.paste": "Pegar",
    "common.cut": "Cortar",
    "common.undo": "Deshacer",
    "common.redo": "Rehacer",

    // Messages
    "msg.welcome": "¡Bienvenido de nuevo!",
    "msg.signInSuccess": "Has iniciado sesión exitosamente.",
    "msg.signOutSuccess": "Has cerrado sesión exitosamente.",
    "msg.accountCreated": "¡Cuenta creada exitosamente!",
    "msg.emailNotConfirmed": "Por favor revisa tu correo para verificar tu cuenta.",
    "msg.messageSent": "¡Mensaje enviado exitosamente!",
    "msg.profileUpdated": "Perfil actualizado exitosamente.",
    "msg.settingsSaved": "Configuración guardada exitosamente.",
    "msg.sessionBooked": "¡Sesión reservada exitosamente!",
    "msg.sessionCancelled": "Sesión cancelada exitosamente.",
    "msg.sessionCompleted": "Sesión marcada como completada.",
    "msg.feedbackSubmitted": "Comentarios enviados exitosamente.",
    "msg.notesUpdated": "Notas actualizadas exitosamente.",
    "msg.error": "Ocurrió un error. Por favor intenta de nuevo.",
    "msg.networkError": "Error de conexión. Verifica tu conexión a internet.",
    "msg.unauthorized": "No tienes autorización para realizar esta acción.",
    "msg.notFound": "El recurso solicitado no fue encontrado.",
    "msg.validationError": "Por favor corrige los errores en el formulario.",
    "msg.confirmDelete": "¿Estás seguro de que quieres eliminar esto?",
    "msg.confirmCancel": "¿Estás seguro de que quieres cancelar?",
    "msg.unsavedChanges": "Tienes cambios sin guardar. ¿Quieres continuar?",

    // Time and Date
    "time.morning": "Mañana",
    "time.afternoon": "Tarde",
    "time.evening": "Noche",
    "time.today": "Hoy",
    "time.tomorrow": "Mañana",
    "time.yesterday": "Ayer",
    "time.thisWeek": "Esta Semana",
    "time.nextWeek": "Próxima Semana",
    "time.thisMonth": "Este Mes",
    "time.nextMonth": "Próximo Mes",
    "time.minutes": "minutos",
    "time.hours": "horas",
    "time.days": "días",
    "time.weeks": "semanas",
    "time.months": "meses",
    "time.years": "años",

    // Subjects
    "subjects.mathematics": "Matemáticas",
    "subjects.physics": "Física",
    "subjects.chemistry": "Química",
    "subjects.biology": "Biología",
    "subjects.computerScience": "Ciencias de la Computación",
    "subjects.english": "Inglés",
    "subjects.spanish": "Español",
    "subjects.french": "Francés",
    "subjects.history": "Historia",
    "subjects.geography": "Geografía",
    "subjects.economics": "Economía",
    "subjects.psychology": "Psicología",
    "subjects.philosophy": "Filosofía",
    "subjects.art": "Arte",
    "subjects.music": "Música",
    "subjects.literature": "Literatura",

    // Roles
    "roles.student": "Estudiante",
    "roles.tutor": "Tutor",
    "roles.admin": "Administrador",

    // Status
    "status.active": "Activo",
    "status.inactive": "Inactivo",
    "status.pending": "Pendiente",
    "status.approved": "Aprobado",
    "status.rejected": "Rechazado",
    "status.suspended": "Suspendido",
    "status.verified": "Verificado",
    "status.unverified": "No Verificado",

    // Notifications
    "notifications.title": "Notificaciones",
    "notifications.markAllRead": "Marcar Todas como Leídas",
    "notifications.noNotifications": "No tienes notificaciones",
    "notifications.sessionReminder": "Recordatorio de Sesión",
    "notifications.newMessage": "Nuevo Mensaje",
    "notifications.bookingConfirmed": "Reserva Confirmada",
    "notifications.bookingCancelled": "Reserva Cancelada",
    "notifications.paymentReceived": "Pago Recibido",
    "notifications.profileUpdated": "Perfil Actualizado",

    // Footer
    "footer.aboutUs": "Acerca de Nosotros",
    "footer.contactUs": "Contáctanos",
    "footer.privacyPolicy": "Política de Privacidad",
    "footer.termsOfService": "Términos de Servicio",
    "footer.help": "Ayuda",
    "footer.support": "Soporte",
    "footer.careers": "Carreras",
    "footer.blog": "Blog",
    "footer.followUs": "Síguenos",
    "footer.allRightsReserved": "Todos los derechos reservados",
    "footer.madeWith": "Hecho con",
    "footer.love": "amor",

    // Shortcuts
    "shortcuts.skipMain": "Saltar al contenido principal",
    "shortcuts.skipNav": "Saltar a la navegación",
    "shortcuts.skipSearch": "Saltar a la búsqueda",
    "shortcuts.toggleContrast": "Alternar alto contraste",
    "shortcuts.toggleMotion": "Alternar movimiento reducido",
    "shortcuts.increaseFontSize": "Aumentar tamaño de fuente",
    "shortcuts.decreaseFontSize": "Disminuir tamaño de fuente",
    "shortcuts.openAccessibility": "Abrir menú de accesibilidad",

    // Validation
    "validation.required": "Este campo es requerido",
    "validation.email": "Ingresa un correo electrónico válido",
    "validation.password": "La contraseña debe tener al menos 8 caracteres",
    "validation.passwordMatch": "Las contraseñas no coinciden",
    "validation.minLength": "Debe tener al menos {min} caracteres",
    "validation.maxLength": "No puede tener más de {max} caracteres",
    "validation.phoneNumber": "Ingresa un número de teléfono válido",
    "validation.url": "Ingresa una URL válida",
    "validation.number": "Ingresa un número válido",
    "validation.positiveNumber": "Debe ser un número positivo",
    "validation.dateFormat": "Formato de fecha inválido",
    "validation.futureDate": "La fecha debe ser en el futuro",
    "validation.pastDate": "La fecha debe ser en el pasado",
  },
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.sessions": "Sessions",
    "nav.search": "Search Tutors",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.signOut": "Sign Out",
    "nav.signIn": "Sign In",
    "nav.signUp": "Sign Up",
    "nav.home": "Home",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.help": "Help",

    // Home Page
    "home.hero.title": "Learn Without Limits",
    "home.hero.subtitle":
      "Connect with expert tutors for personalized academic support. Accessible, inclusive, and designed for every learner.",
    "home.hero.getStarted": "Get Started",
    "home.hero.findTutors": "Find Tutors",
    "home.features.title": "Why Choose TutorHub?",
    "home.features.subtitle":
      "We're committed to making quality education accessible to everyone, with features designed for all learners.",
    "home.accessibility.title": "Committed to Accessibility",
    "home.accessibility.subtitle":
      "TutorHub is designed to be accessible to all users, including those with disabilities. We follow WCAG 2.1 AA guidelines and continuously improve our platform's accessibility features.",
    "home.contact.title": "Get in Touch",
    "home.contact.subtitle": "Have questions? We're here to help you succeed.",

    // Features
    "features.expertTutors": "Expert Tutors",
    "features.expertTutors.desc": "Connect with qualified tutors across all subjects and academic levels.",
    "features.personalizedLearning": "Personalized Learning",
    "features.personalizedLearning.desc": "Get one-on-one attention tailored to your learning style and pace.",
    "features.flexibleScheduling": "Flexible Scheduling",
    "features.flexibleScheduling.desc": "Book sessions that fit your schedule with easy rescheduling options.",
    "features.qualityAssured": "Quality Assured",
    "features.qualityAssured.desc": "All tutors are verified and rated by students for quality assurance.",
    "features.safeSecure": "Safe & Secure",
    "features.safeSecure.desc": "Your privacy and security are our top priorities with encrypted sessions.",
    "features.instantSupport": "Instant Support",
    "features.instantSupport.desc": "Get help when you need it with our responsive support system.",

    // Forms
    "form.required": "required",
    "form.email": "Email Address",
    "form.password": "Password",
    "form.confirmPassword": "Confirm Password",
    "form.fullName": "Full Name",
    "form.signIn": "Sign In",
    "form.signUp": "Create Account",
    "form.loading": "Loading...",
    "form.signingIn": "Signing in...",
    "form.creatingAccount": "Creating account...",
    "form.sendMessage": "Send Message",
    "form.sendingMessage": "Sending message...",
    "form.name": "Name",
    "form.subject": "Subject",
    "form.message": "Message",
    "form.category": "Category",
    "form.phone": "Phone",
    "form.save": "Save",
    "form.cancel": "Cancel",
    "form.edit": "Edit",
    "form.delete": "Delete",
    "form.submit": "Submit",
    "form.reset": "Reset",

    // Search
    "search.title": "Find Your Perfect Tutor",
    "search.subtitle":
      "Search through our network of qualified, verified tutors to find the perfect match for your learning goals.",
    "search.results": "Search Results",
    "search.tutorsFound": "tutors found",
    "search.bookSession": "Book Session",
    "search.sendMessage": "Send Message",
    "search.viewProfile": "View Profile",
    "search.loadMore": "Load More Tutors",
    "search.noResults": "No tutors found",
    "search.tryDifferent": "Try different search filters",
    "search.filters": "Filters",
    "search.clearFilters": "Clear Filters",
    "search.priceRange": "Price Range",
    "search.availability": "Availability",
    "search.rating": "Rating",
    "search.experience": "Experience",
    "search.language": "Language",
    "search.location": "Location",

    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.subtitle": "Here's what's happening with your tutoring sessions.",
    "dashboard.totalSessions": "Total Sessions",
    "dashboard.completed": "Completed",
    "dashboard.upcoming": "Upcoming",
    "dashboard.upcomingSessions": "Upcoming Sessions",
    "dashboard.noSessions": "No upcoming sessions",
    "dashboard.findTutors": "Find Tutors",
    "dashboard.viewSessions": "View All Sessions",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.quickStats": "Quick Stats",
    "dashboard.thisWeek": "This Week",
    "dashboard.thisMonth": "This Month",
    "dashboard.earnings": "Earnings",
    "dashboard.students": "Students",

    // Sessions
    "sessions.title": "My Sessions",
    "sessions.subtitle": "Manage your tutoring sessions",
    "sessions.bookNew": "Book New Session",
    "sessions.filter.all": "All Sessions",
    "sessions.filter.scheduled": "Scheduled",
    "sessions.filter.completed": "Completed",
    "sessions.filter.cancelled": "Cancelled",
    "sessions.filter.inProgress": "In Progress",
    "sessions.status.scheduled": "Scheduled",
    "sessions.status.completed": "Completed",
    "sessions.status.cancelled": "Cancelled",
    "sessions.status.inProgress": "In Progress",
    "sessions.status.noShow": "No Show",
    "sessions.viewDetails": "View Details",
    "sessions.joinMeeting": "Join Meeting",
    "sessions.reschedule": "Reschedule",
    "sessions.cancel": "Cancel",
    "sessions.markComplete": "Mark Complete",
    "sessions.rateTutor": "Rate Tutor",
    "sessions.rateStudent": "Rate Student",
    "sessions.sendMessage": "Send Message",
    "sessions.notes": "Session Notes",
    "sessions.addNotes": "Add Notes",
    "sessions.saveNotes": "Save Notes",
    "sessions.feedback": "Feedback",
    "sessions.submitFeedback": "Submit Feedback",
    "sessions.duration": "Duration",
    "sessions.price": "Price",
    "sessions.tutor": "Tutor",
    "sessions.student": "Student",
    "sessions.subject": "Subject",
    "sessions.date": "Date",
    "sessions.time": "Time",
    "sessions.location": "Location",
    "sessions.online": "Online",
    "sessions.inPerson": "In Person",

    // Profile
    "profile.title": "My Profile",
    "profile.subtitle": "Manage your personal information and account settings",
    "profile.personalInfo": "Personal Information",
    "profile.contactInfo": "Contact Information",
    "profile.professionalInfo": "Professional Information",
    "profile.bio": "Biography",
    "profile.specializations": "Specializations",
    "profile.experience": "Experience",
    "profile.education": "Education",
    "profile.certifications": "Certifications",
    "profile.languages": "Languages",
    "profile.hourlyRate": "Hourly Rate",
    "profile.availability": "Availability",
    "profile.profilePicture": "Profile Picture",
    "profile.uploadPhoto": "Upload Photo",
    "profile.changePhoto": "Change Photo",
    "profile.removePhoto": "Remove Photo",
    "profile.saveChanges": "Save Changes",
    "profile.editProfile": "Edit Profile",
    "profile.viewPublicProfile": "View Public Profile",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account preferences and accessibility options",
    "settings.general": "General",
    "settings.accessibility": "Accessibility",
    "settings.privacy": "Privacy",
    "settings.account": "Account",
    "settings.notifications": "Notifications",
    "settings.security": "Security",
    "settings.theme": "Theme",
    "settings.language": "Language",
    "settings.fontSize": "Font Size",
    "settings.highContrast": "High Contrast",
    "settings.reduceMotion": "Reduce Motion",
    "settings.screenReader": "Screen Reader",
    "settings.keyboardShortcuts": "Keyboard Shortcuts",
    "settings.exportData": "Export Data",
    "settings.deleteAccount": "Delete Account",
    "settings.changePassword": "Change Password",
    "settings.twoFactor": "Two-Factor Authentication",
    "settings.activeSessions": "Active Sessions",
    "settings.privacyControls": "Privacy Controls",
    "settings.dataManagement": "Data Management",

    // Booking
    "booking.title": "Book Session",
    "booking.subtitle": "Schedule a tutoring session",
    "booking.selectSubject": "Select Subject",
    "booking.selectDate": "Select Date",
    "booking.selectTime": "Select Time",
    "booking.duration": "Duration",
    "booking.sessionType": "Session Type",
    "booking.online": "Online",
    "booking.inPerson": "In Person",
    "booking.description": "Session Description",
    "booking.specialRequests": "Special Requests",
    "booking.totalCost": "Total Cost",
    "booking.bookSession": "Book Session",
    "booking.confirmBooking": "Confirm Booking",
    "booking.paymentMethod": "Payment Method",
    "booking.cardNumber": "Card Number",
    "booking.expiryDate": "Expiry Date",
    "booking.cvv": "CVV",
    "booking.billingAddress": "Billing Address",

    // Accessibility
    "a11y.highContrast": "High Contrast",
    "a11y.reduceMotion": "Reduce Motion",
    "a11y.fontSize": "Font Size",
    "a11y.language": "Interface Language",
    "a11y.colorVision": "Color Vision",
    "a11y.customColors": "Custom Colors",
    "a11y.speechSettings": "Speech Settings",
    "a11y.keyboardShortcuts": "Keyboard Shortcuts",
    "a11y.skipToMain": "Skip to main content",
    "a11y.skipToNav": "Skip to navigation",
    "a11y.openMenu": "Open accessibility menu",
    "a11y.closeMenu": "Close accessibility menu",

    // Common
    "common.on": "On",
    "common.off": "Off",
    "common.yes": "Yes",
    "common.no": "No",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.close": "Close",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.clear": "Clear",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Information",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.continue": "Continue",
    "common.finish": "Finish",
    "common.retry": "Retry",
    "common.refresh": "Refresh",
    "common.view": "View",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.select": "Select",
    "common.choose": "Choose",
    "common.upload": "Upload",
    "common.download": "Download",
    "common.print": "Print",
    "common.share": "Share",
    "common.copy": "Copy",
    "common.paste": "Paste",
    "common.cut": "Cut",
    "common.undo": "Undo",
    "common.redo": "Redo",

    // Messages
    "msg.welcome": "Welcome back!",
    "msg.signInSuccess": "You have successfully signed in.",
    "msg.signOutSuccess": "You have successfully signed out.",
    "msg.accountCreated": "Account created successfully!",
    "msg.emailNotConfirmed": "Please check your email to verify your account.",
    "msg.messageSent": "Message sent successfully!",
    "msg.profileUpdated": "Profile updated successfully.",
    "msg.settingsSaved": "Settings saved successfully.",
    "msg.sessionBooked": "Session booked successfully!",
    "msg.sessionCancelled": "Session cancelled successfully.",
    "msg.sessionCompleted": "Session marked as completed.",
    "msg.feedbackSubmitted": "Feedback submitted successfully.",
    "msg.notesUpdated": "Notes updated successfully.",
    "msg.error": "An error occurred. Please try again.",
    "msg.networkError": "Network error. Please check your internet connection.",
    "msg.unauthorized": "You are not authorized to perform this action.",
    "msg.notFound": "The requested resource was not found.",
    "msg.validationError": "Please correct the errors in the form.",
    "msg.confirmDelete": "Are you sure you want to delete this?",
    "msg.confirmCancel": "Are you sure you want to cancel?",
    "msg.unsavedChanges": "You have unsaved changes. Do you want to continue?",

    // Time and Date
    "time.morning": "Morning",
    "time.afternoon": "Afternoon",
    "time.evening": "Evening",
    "time.today": "Today",
    "time.tomorrow": "Tomorrow",
    "time.yesterday": "Yesterday",
    "time.thisWeek": "This Week",
    "time.nextWeek": "Next Week",
    "time.thisMonth": "This Month",
    "time.nextMonth": "Next Month",
    "time.minutes": "minutes",
    "time.hours": "hours",
    "time.days": "days",
    "time.weeks": "weeks",
    "time.months": "months",
    "time.years": "years",

    // Subjects
    "subjects.mathematics": "Mathematics",
    "subjects.physics": "Physics",
    "subjects.chemistry": "Chemistry",
    "subjects.biology": "Biology",
    "subjects.computerScience": "Computer Science",
    "subjects.english": "English",
    "subjects.spanish": "Spanish",
    "subjects.french": "French",
    "subjects.history": "History",
    "subjects.geography": "Geography",
    "subjects.economics": "Economics",
    "subjects.psychology": "Psychology",
    "subjects.philosophy": "Philosophy",
    "subjects.art": "Art",
    "subjects.music": "Music",
    "subjects.literature": "Literature",

    // Roles
    "roles.student": "Student",
    "roles.tutor": "Tutor",
    "roles.admin": "Administrator",

    // Status
    "status.active": "Active",
    "status.inactive": "Inactive",
    "status.pending": "Pending",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.suspended": "Suspended",
    "status.verified": "Verified",
    "status.unverified": "Unverified",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark All as Read",
    "notifications.noNotifications": "You have no notifications",
    "notifications.sessionReminder": "Session Reminder",
    "notifications.newMessage": "New Message",
    "notifications.bookingConfirmed": "Booking Confirmed",
    "notifications.bookingCancelled": "Booking Cancelled",
    "notifications.paymentReceived": "Payment Received",
    "notifications.profileUpdated": "Profile Updated",

    // Footer
    "footer.aboutUs": "About Us",
    "footer.contactUs": "Contact Us",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfService": "Terms of Service",
    "footer.help": "Help",
    "footer.support": "Support",
    "footer.careers": "Careers",
    "footer.blog": "Blog",
    "footer.followUs": "Follow Us",
    "footer.allRightsReserved": "All rights reserved",
    "footer.madeWith": "Made with",
    "footer.love": "love",

    // Shortcuts
    "shortcuts.skipMain": "Skip to main content",
    "shortcuts.skipNav": "Skip to navigation",
    "shortcuts.skipSearch": "Skip to search",
    "shortcuts.toggleContrast": "Toggle high contrast",
    "shortcuts.toggleMotion": "Toggle reduced motion",
    "shortcuts.increaseFontSize": "Increase font size",
    "shortcuts.decreaseFontSize": "Decrease font size",
    "shortcuts.openAccessibility": "Open accessibility menu",

    // Validation
    "validation.required": "This field is required",
    "validation.email": "Please enter a valid email address",
    "validation.password": "Password must be at least 8 characters",
    "validation.passwordMatch": "Passwords do not match",
    "validation.minLength": "Must be at least {min} characters",
    "validation.maxLength": "Cannot be more than {max} characters",
    "validation.phoneNumber": "Please enter a valid phone number",
    "validation.url": "Please enter a valid URL",
    "validation.number": "Please enter a valid number",
    "validation.positiveNumber": "Must be a positive number",
    "validation.dateFormat": "Invalid date format",
    "validation.futureDate": "Date must be in the future",
    "validation.pastDate": "Date must be in the past",
  },
}

export function useLanguage() {
  const { settings } = useAccessibility()

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[settings.language]?.[key] || translations.es[key] || key

    // Replace parameters in translation
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, String(value))
      })
    }

    return translation
  }

  const currentLanguage = settings.language || "es"

  return { t, currentLanguage }
}
